# Generated by Django 5.0.7 on 2024-07-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Victim',
                'verbose_name_plural': 'Victims',
                'db_table': 'victims',
                'ordering': ['username'],
            },
        ),
    ]
